# Generated by Django 4.1.3 on 2022-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='none', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
