# Generated by Django 4.1.3 on 2022-11-12 03:18

import django.core.validators
from django.db import migrations, models
import photo_gallery.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), photo_gallery.accounts.validators.validate_chars], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), photo_gallery.accounts.validators.validate_chars], verbose_name='Last Name'),
        ),
    ]
