# Generated by Django 4.1.3 on 2022-11-13 14:16

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    Photos = apps.get_model("photos", "BasePhotos")

    photos = Photos.objects.all()

    for photo in photos:
        photo.slug = slugify(photo.title)


    Photos.objects.bulk_update(photos, ['slug'])

def delete_slugs(apps, schema_editor):
    Photos = apps.get_model("photos", "BasePhotos")

    photos = Photos.objects.all()

    for photo in photos:
        photo.slug = None

    Photos.objects.bulk_update(photos, ['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_slugs, delete_slugs),
    ]
