# Generated by Django 4.1.3 on 2022-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_add_slugify'),
    ]

    operations = [
        migrations.AddField(
            model_name='basephotos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basephotos',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
