# Generated by Django 4.1.3 on 2022-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_basephotos_description_alter_basephotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basephotos',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
